### ISSUE TITLE
In-page sub-menus styling Mobile

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#25]
Same issue as the Desktop + the sub-menu bar should go full-width as per the initial design (attached)
<img width="755" alt="Screenshot 2020-05-07 at 15 34 32" src="https://user-images.githubusercontent.com/64909873/81301715-b2987580-9079-11ea-9cb1-9bfd413973af.png">

**Comment by Mai-tbaileh** [comment]
in the mookups I had two designs for the menu 
![menu 2](https://user-images.githubusercontent.com/48549937/82201038-6f0afa80-9908-11ea-9201-a47a0040da36.JPG)
![menu1](https://user-images.githubusercontent.com/48549937/82201043-703c2780-9908-11ea-9250-565fccda9742.JPG)


So in your comments i will use menu2 and update it for all the pages right??? in order to be consistent

**Comment by giorgiouboldi** [comment]
Yes go for menu2, sorry for the wrong design
